server:
  servlet:
    context-path: /geekshop

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/geekbrains?useUnicode=true&characterEncoding=UTF8
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: shopgeekbrains@gmail.com
    password: geekbrains.ru
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  thymeleaf:
    cache: false
files:
  storepath:
    icons:  "//Users//ruaadv7//Documents//GeekBrains//uploads//icons"
    images: "//Users//ruaadv7//Documents//GeekBrains//uploads//images"

geekshop:
  rabbitmq:
    exchange: super-shop.exchange
    routingkey: super.shop
    queue: super-shop.queue

documents:
  service:
    url: "localhost:10210/documents"